### ISSUE TITLE
Changed BASE_URL in 2.2.0 release and job search with Upwork GraphQL API

### ISSUE THREAD

**Issue by andriisly** [upwork/java-upwork-oauth2#13]
In [the 2.2.0 release](https://github.com/upwork/java-upwork-oauth2/compare/v2.1.3...v2.2.0#diff-058f9e679e1234c503b17a67f35d2ea466fca9823da4833285b0cd76cda89fceR45-R47:~:text=private%20static%20final%20String%20UPWORK_BASE_URL%20%3D%20%22https%3A//stage.upwork.com/%22%3B), the BASE_URL subdomain was changed from "**_www_**" to "**_stage_**". If looking at the same BASE_URL in other libraries, such as ["upwork/node-upwork-oauth2"](https://github.com/upwork/node-upwork-oauth2/compare/v2.2.0...v2.2.1), it has been changed back to "https://**_www_**.upwork.com/". **It looks like this library also needs to return the previous subdomain**.

Additionally, **do you have plans to include job search support in the new Upwork GraphQL API? If you do, when is it expected to be added?** Because the option to search for jobs in the Upwork REST API will not work after December 15, 2023.

**Comment by mnovozhylov** [comment]
@AndriiSlynko thank you! That's a typo and will be fixed ASAP.
Regarding GraphQL and ETAs, please, reach out to the Support Team.
